### ISSUE TITLE
Licence issue

### ISSUE THREAD

**Issue by LimHyungTae** [cocel-postech/genz-icp#1]
Hey @Daehan2Lee,

It could be a minor thing,

but I believe all the ` Copyright (c) 2024 Daehan Lee, Hyungtae Lim, and Soohee Han.` part should be modified to 

```
# Copyright (c) 2022 Ignacio Vizzo, Tiziano Guadagnino, Benedikt Mersch, Cyrill Stachniss.
# Modified by Daehan Lee, Hyungtae Lim, and Soohee Han, 2024
```
in order to preserve the original authors' contribution.

**Comment by Daehan2Lee** [comment]
Thank you for your advice regarding the license! I’ve updated the copyright as you suggested!
