### ISSUE TITLE
Long_Corridor packet 

### ISSUE THREAD

**Issue by ElaineChen10** [cocel-postech/genz-icp#3]
The /velodyne_points download link for the Long_Corridor packet in the SubT-MRS dataset is no longer accessible, can you provide a new download method?

**Comment by Daehan2Lee** [comment]
The download link is still available.
Please try again, and if you still can’t download it, you can use the following link instead.

https://postechackr-my.sharepoint.com/:u:/g/personal/daehanlee_postech_ac_kr/EdszUZkg3YpLsaVaN6vZgxoBf1ihnmhSyboAHVnoP_n2lQ?e=hsY6to

**Comment by Daehan2Lee** [comment]
I noticed that the link wasn’t working for some users, so I updated it.
You can now download the file using the following command in the terminal:

`wget https://postechackr-my.sharepoint.com/:u:/g/personal/daehanlee_postech_ac_kr/EduGeuaT5ypBvSQY539XFEgBRSsQSUopeNjalk9jJqyq5Q?e=2IM8ed&download=1 -O subt_mrs_long_corridor.zip`
