### ISSUE TITLE
Which sequences of MulRan dataset are used in the paper results?

### ISSUE THREAD

**Issue by engcang** [cocel-postech/genz-icp#4]
Hi @Daehan2Lee !
Great to see you again online and congratulations on your great works acceptance for the publication!

I would like to reproduce the results of your on MulRan dataset, but the indices of each sequence are not represented in the paper.
Which sequences are used in the paper? e.g., DCC-1, KAIST-2, Riverside-3, Sejong-2.

**Comment by Daehan2Lee** [comment]
Thank you so much! Eungchang. It's a pleasure to see you again! 

The results of the MulRan dataset represent the average values derived by using all indices for each sequence, as done in the KISS-ICP paper.

Additionally, the evaluation was conducted by pybinding GenZ-ICP and importing it into the KISS-ICP's evaluation script (https://github.com/PRBonn/kiss-icp/blob/main/eval/mulran.ipynb) in place of KISS-ICP.

**Comment by engcang** [comment]
Got it. Thank you man~~~!!!
